### ISSUE TITLE
 the number of samples involved in the training of the target domain

### ISSUE THREAD

**Issue by HopePersist** [YuxiangZhang-BIT/IEEE_TNNLS_TSTnet#2]
Sorry to bother you, your article is excellent and helped me a lot and thank you very much for sharing the corresponding code. However, I have a small question that I would like to get an answer from you.

Specifically, the training set of the source domain is 5% of the total samples, so does the number of samples involved in the training of the target domain need to be consistent with the number of training samples of the source domain? If not, will the training process result in a mismatch in the number of training samples which leads to failure to load the dataloader into the model?

I look forward to your reply.
thanks！

**Comment by zhuwenxaing** [comment]
`        if 0 < (len_tar_train_dataset-i*bs) < bs or i % len_tar_train_loader == 0:
            iter_target = data_prefetcher(train_tar_loader)`   （train.py）
