### ISSUE TITLE
Houston Datasets

### ISSUE THREAD

**Issue by efkandurakli** [YuxiangZhang-BIT/IEEE_TNNLS_TSTnet#3]
Regarding the Houston datasets that you used in your paper, you are saying that you extracted 48 bands from Houston 2013 corresponding to Houston 2018 and selected the overlapping area of 209 x 955. How did you obtain this area? Would you mind if you could share the dataset?

**Comment by YuxiangZhang-BIT** [comment]
Related data has been open source, see the Data-CSHSI repository [https://github.com/YuxiangZhang-BIT/Data-CSHSI](url)

**Comment by efkandurakli** [comment]
Thank you very much for sharing the datasets.
